// -*- coding: utf-8 -*-
// 运行时 emoji → Lucide 图标名映射（与 _icon_migration/_mapping.tsv 保持一致）
// 用于动态/API 数据驱动的图标渲染；静态模板已直接用 <text class="luc luc-xxx">

const EMOJI_MAP = {
  "👁‍🗨": 'message-circle',
  "🐈‍⬛": 'paw-print',
  "🛍️": 'shopping-bag',
  "🛡️": 'shield',
  "❤️": 'heart',
  "⚠️": 'alert-triangle',
  "✏️": 'pencil',
  "✂️": 'scissors',
  "🖼️": 'image',
  "🎟️": 'ticket',
  "🏷️": 'tag',
  "✉️": 'mail',
  "⚖️": 'scale',
  "👁🗨": 'eye-off',
  "✨": 'sparkles',
  "🎁": 'gift',
  "💬": 'message-circle',
  "🔍": 'search',
  "📦": 'package',
  "🔔": 'bell',
  "🏆": 'trophy',
  "🔗": 'link',
  "📱": 'smartphone',
  "⚡": 'zap',
  "👤": 'user',
  "📍": 'map-pin',
  "🕐": 'clock',
  "🔒": 'lock',
  "📷": 'camera',
  "👁": 'eye',
  "♥": 'heart',
  "🔥": 'flame',
  "🔄": 'refresh-cw',
  "🐕": 'paw-print',
  "🐈": 'paw-print',
  "🐱": 'paw-print',
  "✅": 'check-circle',
  "📭": 'inbox',
  "🎟": 'ticket',
  "🛡": 'shield',
  "❓": 'help-circle',
  "🛒": 'shopping-cart',
  "🎫": 'ticket',
  "📤": 'upload',
  "🛍": 'shopping-bag',
  "👍": 'thumbs-up',
  "🚚": 'truck',
  "📄": 'file-text',
  "⚠": 'alert-triangle',
  "➖": 'minus',
  "🧾": 'receipt',
  "📈": 'trending-up',
  "➕": 'plus',
  "📋": 'clipboard-list',
  "📅": 'calendar',
  "🖼": 'image',
  "🏷": 'tag',
  "🏠": 'home',
  "🧴": 'spray-can',
  "➤": 'send',
  "🔦": 'flashlight',
  "👥": 'users',
  "🤍": 'heart',
  "💡": 'lightbulb',
  "📜": 'scroll-text',
  "🎧": 'headphones',
  "👩": 'user',
  "♻": 'recycle',
  "💰": 'banknote',
  "📊": 'bar-chart',
  "📖": 'book',
  "🏦": 'building-2',
  "📔": 'book',
  "🍽": 'utensils',
  "⚙": 'settings',
  "🛁": 'bath',
  "🦷": 'brush',
  "❤": 'heart',
  "♡": 'heart',
  "🙈": 'eye-off',
  "🎉": 'party-popper',
  "👎": 'thumbs-down',
  "📘": 'book',
  "📞": 'phone',
  "☆": 'star',
  "🔑": 'key',
  "💻": 'laptop',
  "🔀": 'shuffle',
  "🌙": 'moon',
  "🌐": 'globe',
  "👑": 'crown',
  "🗨": 'message-circle',
  "⭐": 'star',
  "💳": 'credit-card',
  "📶": 'signal',
  "🖥": 'monitor',
  "😊": 'smile',
  "😌": 'smile',
  "💊": 'pill',
  "💉": 'syringe',
  "🩺": 'stethoscope',
  "📝": 'edit-3',
  "📌": 'map-pin',
  "🎾": 'paw-print',
  "🍗": 'utensils',
  "🐾": 'paw-print',
  "♀": 'user',
  "♂": 'user',
  "🎒": 'shopping-bag',
  "📸": 'camera',
  "🎯": 'target',
  "🤝": 'handshake',
  "👣": 'footprints',
  "🐧": 'paw-print',
  "💚": 'heart',
  "💙": 'heart',
  "🤖": 'cpu',
  "📹": 'video',
  "‹": 'arrow-left',
  "›": 'chevron-right',
  "✓": 'check',
  "✕": 'x',
  "×": 'x',
  "★": 'star',
  "←": 'arrow-left',
  "→": 'arrow-right',
  "✦": 'sparkles',
  "✗": 'x',
  "✧": 'sparkles',
  "⚖": 'scale',
  "✂": 'scissors',
  "✉": 'mail',
  "🍎": 'apple',
  "🏥": 'cross',
  "👗": 'shirt',
  "🗺": 'map',
  "🧠": 'brain',
  "⌕": 'search',
}

/**
 * 把 emoji 或已有图标名统一转为 luc 类名；空值返回空串。
 * 用法：<text class="luc" :class="$luc(item.icon)"></text>
 */
export function lucClass(v) {
  if (!v) return ''
  const name = EMOJI_MAP[v] || v
  return name ? 'luc luc-' + name : ''
}
