-- 订单打印模板：新增 content_template 列，保存 HTML 模板正文
-- 与 OrderPrint.vue 编辑对话框的"模板内容"textarea 对接：
--   - 空字符串 = 使用代码里写的默认模板（保持向后兼容）
--   - 非空 = 打印时按此 HTML 渲染，前端做占位符 {{order.xxx}} 替换 + HTML 转义
-- 使用 MEDIUMTEXT（16MB 上限）而非 TEXT（64KB 上限），允许运营做复杂的配货标签模板。
ALTER TABLE `mo_print_template`
  ADD COLUMN `content_template` MEDIUMTEXT DEFAULT NULL
    COMMENT '模板 HTML 正文（占位符语法 {{order.xxx}} / {{items}}），空=用代码默认模板'
  AFTER `description`;

-- 默认电商模板 HTML（拣货/打包/发货/配货四种）：
-- 设计要点：
--   1) 占位符双花括号 {{order.orderNo}} / {{items}} / {{time}} / {{paper}}，与前端 replaceTokens() 协议
--   2) 内联 CSS：打印时不依赖外部样式，且 @media print 自动适配
--   3) 表格边框用 border-collapse:collapse，单元格 padding 2px 6px 兼容热敏纸
--   4) {{items}} 整段替换为商品明细 HTML（前端 OrderPrint.vue 的 buildItemsHtml() 生成）
-- 5) SHIPPING_LABEL 不存默认（保留空，走燕文 PDF 渲染）
UPDATE `mo_print_template` SET `content_template` = '<div class="moyu-tpl moyu-tpl-pick"><h1>{{template.name}}</h1><div class="meta">打印时间：{{time}}　|　纸张：{{paper}}</div><table class="info"><tr><th>订单编号</th><td>{{order.orderNo}}</td><th>下单时间</th><td>{{order.createTime}}</td></tr></table><h2>拣货明细（按货位）</h2><div class="items">{{items}}</div><div class="footer">拣货员签字：__________________　复核：__________________</div></div><style>.moyu-tpl-pick{font-family:monospace;font-size:12px;color:#000}.moyu-tpl-pick h1{font-size:20px;text-align:center;margin:0 0 8px;border-bottom:2px solid #000;padding-bottom:6px}.moyu-tpl-pick .meta{text-align:center;font-size:11px;color:#555;margin-bottom:12px}.moyu-tpl-pick h2{font-size:14px;margin:12px 0 6px}.moyu-tpl-pick table.info{width:100%;border-collapse:collapse;margin-bottom:8px}.moyu-tpl-pick table.info th,.moyu-tpl-pick table.info td{border:1px solid #000;padding:4px 8px;text-align:left;font-size:12px}.moyu-tpl-pick table.info th{background:#f0f0f0;width:80px}.moyu-tpl-pick table.items{width:100%;border-collapse:collapse}.moyu-tpl-pick table.items th,.moyu-tpl-pick table.items td{border:1px solid #000;padding:4px 6px;font-size:11px}.moyu-tpl-pick table.items th{background:#e8e8e8}.moyu-tpl-pick .footer{margin-top:16px;font-size:11px;border-top:1px dashed #000;padding-top:8px}</style>' WHERE `code` = 'PICK';

UPDATE `mo_print_template` SET `content_template` = '<div class="moyu-tpl moyu-tpl-pack"><h1>{{template.name}}</h1><div class="meta">订单号：{{order.orderNo}}　|　打印：{{time}}</div><table class="info"><tr><th>收件人</th><td>{{order.receiverName}}</td></tr><tr><th>电话</th><td>{{order.receiverPhone}}</td></tr><tr><th>地址</th><td>{{order.receiverAddress}}</td></tr><tr><th>备注</th><td>{{order.remark}}</td></tr></table><h2>商品清单</h2><div class="items">{{items}}</div><div class="footer">打包员：________　复核：________</div></div><style>.moyu-tpl-pack{font-family:sans-serif;font-size:12px;color:#000}.moyu-tpl-pack h1{font-size:18px;text-align:center;margin:0 0 8px}.moyu-tpl-pack .meta{text-align:center;font-size:11px;color:#666;margin-bottom:10px}.moyu-tpl-pack h2{font-size:13px;margin:10px 0 6px;background:#f5f5f5;padding:4px 8px}.moyu-tpl-pack table.info{width:100%;border-collapse:collapse}.moyu-tpl-pack table.info th,.moyu-tpl-pack table.info td{border:1px solid #999;padding:4px 8px;text-align:left;font-size:11px}.moyu-tpl-pack table.info th{background:#f5f5f5;width:70px}.moyu-tpl-pack table.items{width:100%;border-collapse:collapse}.moyu-tpl-pack table.items th,.moyu-tpl-pack table.items td{border:1px solid #999;padding:4px 6px;font-size:11px}.moyu-tpl-pack .footer{margin-top:12px;font-size:11px;border-top:1px dashed #999;padding-top:6px}</style>' WHERE `code` = 'PACK';

UPDATE `mo_print_template` SET `content_template` = '<div class="moyu-tpl moyu-tpl-ship"><div class="top-bar">状态：{{order.statusLabel}}　实付：{{order.payAmount}}</div><h1>{{template.name}}</h1><table class="info"><tr><th>订单编号</th><td>{{order.orderNo}}</td></tr><tr><th>下单时间</th><td>{{order.createTime}}</td></tr><tr><th>收件人</th><td>{{order.receiverName}}</td></tr><tr><th>电话</th><td>{{order.receiverPhone}}</td></tr><tr><th>地址</th><td>{{order.receiverAddress}}</td></tr><tr><th>买家备注</th><td>{{order.remark}}</td></tr><tr><th>物流</th><td>{{order.shippingCarrier}} {{order.trackingNumber}}</td></tr></table><h2>商品明细</h2><div class="items">{{items}}</div><div class="footer">MOYUYO 订单发货单 · 打印时间：{{time}} · 纸张：{{paper}}</div></div><style>.moyu-tpl-ship{font-family:sans-serif;font-size:12px;color:#000}.moyu-tpl-ship .top-bar{background:#fff7ed;border:1px solid #ffedd5;color:#c2410c;padding:4px 10px;font-size:11px;border-radius:4px;margin-bottom:8px;text-align:center;font-weight:700}.moyu-tpl-ship h1{font-size:18px;text-align:center;margin:8px 0;border-top:2px solid #000;border-bottom:1px solid #000;padding:6px 0}.moyu-tpl-ship table.info{width:100%;border-collapse:collapse;margin:6px 0}.moyu-tpl-ship table.info th,.moyu-tpl-ship table.info td{border:1px solid #000;padding:5px 8px;text-align:left;font-size:12px}.moyu-tpl-ship table.info th{background:#f0f0f0;width:90px;font-weight:700}.moyu-tpl-ship h2{font-size:14px;margin:10px 0 4px;color:#000}.moyu-tpl-ship table.items{width:100%;border-collapse:collapse}.moyu-tpl-ship table.items th,.moyu-tpl-ship table.items td{border:1px solid #000;padding:4px 6px;font-size:11px}.moyu-tpl-ship table.items th{background:#e8e8e8}.moyu-tpl-ship .footer{margin-top:14px;text-align:center;font-size:10px;color:#666;border-top:1px solid #999;padding-top:6px}</style>' WHERE `code` = 'SHIP';

UPDATE `mo_print_template` SET `content_template` = '<div class="moyu-tpl moyu-tpl-label"><div class="from"><strong>发货：</strong>MOYUYO 海外仓</div><div class="to"><h1>{{order.receiverName}}　{{order.receiverPhone}}</h1><div class="addr">{{order.receiverAddress}}</div></div><div class="bar"><div>订单：{{order.orderNo}}</div><div>{{order.createTime}}</div></div></div><style>.moyu-tpl-label{font-family:sans-serif;color:#000;padding:4mm}.moyu-tpl-label .from{font-size:11px;border-bottom:1px dashed #000;padding-bottom:4px;margin-bottom:8px}.moyu-tpl-label .to h1{font-size:18px;font-weight:700;margin:0 0 6px;letter-spacing:0.5px}.moyu-tpl-label .to .addr{font-size:14px;line-height:1.4;border:1px solid #000;padding:6px;min-height:30mm}.moyu-tpl-label .bar{display:flex;justify-content:space-between;font-size:10px;margin-top:8px;border-top:1px solid #000;padding-top:4px;font-family:monospace}</style>' WHERE `code` = 'LABEL';