-- 同步 mo_coupon 表所有列，与 CouponEntity 和 schema-test.sql 对齐
-- 缺失的列：description, discount_value, max_discount_amount, claimed_count, used_count, end_time, active, update_time
-- 旧列 amount/remain/status/total/min_amount 暂不删除，保留以兼容旧代码

-- 1) description
SET @sql = (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='mo_coupon' AND COLUMN_NAME='description')=0,
  'ALTER TABLE `mo_coupon` ADD COLUMN `description` VARCHAR(500) NULL AFTER `name`', 'SELECT 1'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- 2) discount_value
SET @sql = (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='mo_coupon' AND COLUMN_NAME='discount_value')=0,
  'ALTER TABLE `mo_coupon` ADD COLUMN `discount_value` DECIMAL(10,2) NULL AFTER `type`', 'SELECT 1'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- 3) max_discount_amount
SET @sql = (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='mo_coupon' AND COLUMN_NAME='max_discount_amount')=0,
  'ALTER TABLE `mo_coupon` ADD COLUMN `max_discount_amount` DECIMAL(10,2) NULL', 'SELECT 1'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- 4) total_count
SET @sql = (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='mo_coupon' AND COLUMN_NAME='total_count')=0,
  'ALTER TABLE `mo_coupon` ADD COLUMN `total_count` INT NULL', 'SELECT 1'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- 5) claimed_count
SET @sql = (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='mo_coupon' AND COLUMN_NAME='claimed_count')=0,
  'ALTER TABLE `mo_coupon` ADD COLUMN `claimed_count` INT DEFAULT 0', 'SELECT 1'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- 6) used_count
SET @sql = (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='mo_coupon' AND COLUMN_NAME='used_count')=0,
  'ALTER TABLE `mo_coupon` ADD COLUMN `used_count` INT DEFAULT 0', 'SELECT 1'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- 7) end_time
SET @sql = (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='mo_coupon' AND COLUMN_NAME='end_time')=0,
  'ALTER TABLE `mo_coupon` ADD COLUMN `end_time` DATETIME NULL', 'SELECT 1'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- 8) active
SET @sql = (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='mo_coupon' AND COLUMN_NAME='active')=0,
  'ALTER TABLE `mo_coupon` ADD COLUMN `active` TINYINT(1) DEFAULT 1', 'SELECT 1'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- 9) update_time
SET @sql = (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='mo_coupon' AND COLUMN_NAME='update_time')=0,
  'ALTER TABLE `mo_coupon` ADD COLUMN `update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP', 'SELECT 1'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
